FROM ubuntu

ENTRYPOINT echo "hello world"

# ENTRYPOINT ["echo","hello world"]

# build image: docker build -t entrypoint .

# hello world: docker run entrypoint

# hello world: docker run entrypoint echo "hi"