FROM ubuntu

ENV KEY  'TEST'
ENV NAME  'NAME'

MAINTAINER "TEST@MAIL.COM"

LABEL key1="val1"

LABEL description="This text illustrates \
that label-values can span multiple lines."

EXPOSE 3000

# docker build -t file .
# docker inspect file