version: "3.9"
# services refer to containers' configuration
services:
  # container 1
  FE:
    # pull the image
    image: ubuntu:latest
    # build the image. path to Dockerfile
    build: .
    # define ports
    ports:
      - "80:80"
    # define network
    networks:
      - network_name
    volumes:
      - /opt/path:/dash
    depends_on:
      - BE
    environment:
      - PORT: 3000
  # container 2
  BE:
  # container 3
  DB:

# define volumes here
volumes:
  volume_name: {}

# define networks here
networks:
  network_name: {}


#Commands
#  build              Build or rebuild services
#  bundle             Generate a Docker bundle from the Compose file
#  config             Validate and view the Compose file
#  create             Create services
#  down               Stop and remove containers, networks, images, and volumes
#  events             Receive real time events from containers
#  exec               Execute a command in a running container
#  help               Get help on a command
#  images             List images
#  kill               Kill containers
#  logs               View output from containers
#  pause              Pause services
#  port               Print the public port for a port binding
#  ps                 List containers
#  pull               Pull service images
#  push               Push service images
#  restart            Restart services
#  rm                 Remove stopped containers
#  run                Run a one-off command
#  scale              Set number of containers for a service
#  start              Start services
#  stop               Stop services
#  top                Display the running processes
#  unpause            Unpause services
#  up                 Create and start containers
#  version            Show the Docker-Compose version information